name: Cron Job

on:
  schedule:
    - cron: '0 0 * * *'  # Ejecutar diariamente a la medianoche

jobs:
  run_script:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8.7

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install python-dotenv

    - name: Run script
      run: |
        python -m dotenv scraper.py
