name: Cron Job 

on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  run_script:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8.x
        
    - name: Install python3-distutils
      run: pip install disutils

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt 
        pip install lxml

    - name: Run script
      env:        
          API_AUTH_URL         : ${{ secrets.API_AUTH_URL }}  
          API_PLAYER_STATS_URL : ${{ secrets.API_PLAYER_STATS_URL }}
          API_PLAYERS_URL      : ${{ secrets.API_PLAYERS_URL }} 
          EMAIL                : ${{ secrets.EMAIL }}
          PASSWORD             : ${{ secrets.PASSWORD }} 
      run: |        
        python scraper.py
